import { apiPlugin, storyblokInit } from '@storyblok/react';
import StoryblokComponents from '../components/components-list';
import i18n from '../i18n';

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: StoryblokComponents,
});

export default function RootLayout({ children, params }: {
  children: React.ReactNode; params: { locale: string } }) {
  if (params.locale !== i18n.language) {
    i18n.changeLanguage(params.locale);
  }

  return (
    <html lang={params.locale} dir={i18n.dir(params.locale)}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
